// Test setup file
// Generated by SDK Generator

// Global test setup
beforeAll(() => {
  // Setup code that runs before all tests
});

afterAll(() => {
  // Cleanup code that runs after all tests
});

// Mock global fetch if not available
if (!global.fetch) {
  global.fetch = jest.fn();
}

// Custom matchers or global test utilities can go here
