package com.example.client.models;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.BeforeEach;

import static org.junit.jupiter.api.Assertions.*;

import com.fasterxml.jackson.databind.ObjectMapper;

/**
 * Unit tests for GraphQLRequest model
 * Generated by SDK Generator
 */
@DisplayName("GraphQLRequest Model Tests")
public class GraphQLRequestTest {
    
    private ObjectMapper objectMapper;
    private GraphQLRequest model;
    
    @BeforeEach
    void setUp() {
        objectMapper = new ObjectMapper();
        model = new GraphQLRequest();
    }
    
    @Test
    @DisplayName("Should set and get query")
    void testQueryGetterSetter() {
        // Given
        String expectedValue = "test_value";
        
        // When
        model.setQuery(expectedValue);
        String actualValue = model.getQuery();
        
        // Then
        assertEquals(expectedValue, actualValue);
    }
    
    @Test
    @DisplayName("Should support fluent query setting")
    void testQueryFluentSetter() {
        // Given
        String value = "test_value";
        
        // When
        GraphQLRequest result = model.withQuery(value);
        
        // Then
        assertSame(model, result);
        assertEquals(value, model.getQuery());
    }
    
    @Test
    @DisplayName("Should serialize to JSON")
    void testSerialization() throws Exception {
        // Given
        GraphQLRequest model = new GraphQLRequest();
        // TODO: Set test data
        
        // When
        String json = objectMapper.writeValueAsString(model);
        
        // Then
        assertNotNull(json);
        assertFalse(json.isEmpty());
    }
    
    @Test
    @DisplayName("Should deserialize from JSON")
    void testDeserialization() throws Exception {
        // Given
        String json = "{}"; // TODO: Add valid JSON
        
        // When
        GraphQLRequest result = objectMapper.readValue(json, GraphQLRequest.class);
        
        // Then
        assertNotNull(result);
    }
    
    @Test
    @DisplayName("Should handle round-trip serialization")
    void testRoundTripSerialization() throws Exception {
        // Given
        GraphQLRequest original = new GraphQLRequest();
        // TODO: Set test data
        
        // When
        String json = objectMapper.writeValueAsString(original);
        GraphQLRequest deserialized = objectMapper.readValue(json, GraphQLRequest.class);
        
        // Then
        assertEquals(original, deserialized);
    }
    
    @Test
    @DisplayName("Should implement equals correctly")
    void testEquals() {
        // Given
        GraphQLRequest model1 = new GraphQLRequest();
        GraphQLRequest model2 = new GraphQLRequest();
        GraphQLRequest model3 = new GraphQLRequest();
        
        // TODO: Set same data for model1 and model2
        // TODO: Set different data for model3
        
        // When/Then
        assertEquals(model1, model2);
        assertNotEquals(model1, model3);
        assertEquals(model1, model1);
        assertNotEquals(model1, null);
        assertNotEquals(model1, "different type");
    }
    
    @Test
    @DisplayName("Should implement hashCode correctly")
    void testHashCode() {
        // Given
        GraphQLRequest model1 = new GraphQLRequest();
        GraphQLRequest model2 = new GraphQLRequest();
        
        // TODO: Set same data for both models
        
        // When/Then
        assertEquals(model1.hashCode(), model2.hashCode());
    }
    
    @Test
    @DisplayName("Should implement toString correctly")
    void testToString() {
        // Given
        GraphQLRequest model = new GraphQLRequest();
        
        // When
        String result = model.toString();
        
        // Then
        assertNotNull(result);
        assertTrue(result.contains("GraphQLRequest"));
    }
    
}
