package com.example.client.models;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.BeforeEach;

import static org.junit.jupiter.api.Assertions.*;

import com.fasterxml.jackson.databind.ObjectMapper;

/**
 * Unit tests for Error model
 * Generated by SDK Generator
 */
@DisplayName("Error Model Tests")
public class ErrorTest {
    
    private ObjectMapper objectMapper;
    private Error model;
    
    @BeforeEach
    void setUp() {
        objectMapper = new ObjectMapper();
        model = new Error();
    }
    
    @Test
    @DisplayName("Should set and get code")
    void testCodeGetterSetter() {
        // Given
        Integer expectedValue = 123;
        
        // When
        model.setCode(expectedValue);
        Integer actualValue = model.getCode();
        
        // Then
        assertEquals(expectedValue, actualValue);
    }
    
    @Test
    @DisplayName("Should support fluent code setting")
    void testCodeFluentSetter() {
        // Given
        Integer value = 123;
        
        // When
        Error result = model.withCode(value);
        
        // Then
        assertSame(model, result);
        assertEquals(value, model.getCode());
    }
    
    @Test
    @DisplayName("Should set and get message")
    void testMessageGetterSetter() {
        // Given
        String expectedValue = "test_value";
        
        // When
        model.setMessage(expectedValue);
        String actualValue = model.getMessage();
        
        // Then
        assertEquals(expectedValue, actualValue);
    }
    
    @Test
    @DisplayName("Should support fluent message setting")
    void testMessageFluentSetter() {
        // Given
        String value = "test_value";
        
        // When
        Error result = model.withMessage(value);
        
        // Then
        assertSame(model, result);
        assertEquals(value, model.getMessage());
    }
    
    @Test
    @DisplayName("Should set and get details")
    void testDetailsGetterSetter() {
        // Given
        String expectedValue = "test_value";
        
        // When
        model.setDetails(expectedValue);
        String actualValue = model.getDetails();
        
        // Then
        assertEquals(expectedValue, actualValue);
    }
    
    @Test
    @DisplayName("Should support fluent details setting")
    void testDetailsFluentSetter() {
        // Given
        String value = "test_value";
        
        // When
        Error result = model.withDetails(value);
        
        // Then
        assertSame(model, result);
        assertEquals(value, model.getDetails());
    }
    
    @Test
    @DisplayName("Should serialize to JSON")
    void testSerialization() throws Exception {
        // Given
        Error model = new Error();
        // TODO: Set test data
        
        // When
        String json = objectMapper.writeValueAsString(model);
        
        // Then
        assertNotNull(json);
        assertFalse(json.isEmpty());
    }
    
    @Test
    @DisplayName("Should deserialize from JSON")
    void testDeserialization() throws Exception {
        // Given
        String json = "{}"; // TODO: Add valid JSON
        
        // When
        Error result = objectMapper.readValue(json, Error.class);
        
        // Then
        assertNotNull(result);
    }
    
    @Test
    @DisplayName("Should handle round-trip serialization")
    void testRoundTripSerialization() throws Exception {
        // Given
        Error original = new Error();
        // TODO: Set test data
        
        // When
        String json = objectMapper.writeValueAsString(original);
        Error deserialized = objectMapper.readValue(json, Error.class);
        
        // Then
        assertEquals(original, deserialized);
    }
    
    @Test
    @DisplayName("Should implement equals correctly")
    void testEquals() {
        // Given
        Error model1 = new Error();
        Error model2 = new Error();
        Error model3 = new Error();
        
        // TODO: Set same data for model1 and model2
        // TODO: Set different data for model3
        
        // When/Then
        assertEquals(model1, model2);
        assertNotEquals(model1, model3);
        assertEquals(model1, model1);
        assertNotEquals(model1, null);
        assertNotEquals(model1, "different type");
    }
    
    @Test
    @DisplayName("Should implement hashCode correctly")
    void testHashCode() {
        // Given
        Error model1 = new Error();
        Error model2 = new Error();
        
        // TODO: Set same data for both models
        
        // When/Then
        assertEquals(model1.hashCode(), model2.hashCode());
    }
    
    @Test
    @DisplayName("Should implement toString correctly")
    void testToString() {
        // Given
        Error model = new Error();
        
        // When
        String result = model.toString();
        
        // Then
        assertNotNull(result);
        assertTrue(result.contains("Error"));
    }
    
}
