/**
 * UserService gRPC API TypeScript gRPC SDK Configuration
 * Generated by client-sdk-generator
 */


/**
 * Retry configuration options
 */
export interface RetryConfig {
  /** Maximum number of retry attempts */
  maxRetries: number;
  /** Base delay between retries in milliseconds */
  baseDelay: number;
  /** Maximum delay between retries in milliseconds */
  maxDelay: number;
  /** Exponential backoff multiplier */
  backoffMultiplier: number;
  /** gRPC status codes that should trigger a retry */
  retryableStatusCodes: number[];
}


/**
 * Telemetry configuration options
 */
export interface TelemetryConfig {
  /** Enable or disable telemetry */
  enabled: boolean;
  /** Endpoint for sending metrics */
  metricsEndpoint?: string;
  /** Service name for telemetry */
  serviceName: string;
}

/**
 * gRPC-specific configuration options
 */
export interface GrpcConfig {
  /** Use TLS for the connection */
  useTLS: boolean;
  /** Server name for TLS verification */
  tlsServerName?: string;
  /** Maximum message size in bytes */
  maxMessageSize: number;
  /** Keep-alive interval in milliseconds */
  keepAliveInterval: number;
  /** Keep-alive timeout in milliseconds */
  keepAliveTimeout: number;
  /** Enable keep-alive pings */
  enableKeepAlive: boolean;
}

/**
 * Client configuration options for UserService gRPC API gRPC API
 */
export interface ClientConfig {
  /** gRPC server address (e.g., "localhost:50051") */
  baseURL: string;
  
  /** Request timeout in milliseconds */
  timeout?: number;
  
  /** User agent string */
  userAgent?: string;
  
  
  /** Retry configuration */
  retry?: RetryConfig;
  
  
  /** Telemetry configuration */
  telemetry?: TelemetryConfig;
  
  /** gRPC-specific configuration */
  grpc?: GrpcConfig;
  
  /** Enable debug logging */
  debug?: boolean;
}

/**
 * Default configuration values
 */
export const DEFAULT_CONFIG: Partial<ClientConfig> = {
  timeout: 30000, // 30 seconds
  userAgent: 'com.example.client-grpc-client/1.0.0',
  retry: {
    maxRetries: 3,
    baseDelay: 1000,
    maxDelay: 10000,
    backoffMultiplier: 2,
    retryableStatusCodes: [14, 8, 4], // UNAVAILABLE, RESOURCE_EXHAUSTED, DEADLINE_EXCEEDED
  },
  telemetry: {
    enabled: true,
    serviceName: 'com.example.client-grpc-client',
  },
  grpc: {
    useTLS: false,
    maxMessageSize: 4 * 1024 * 1024, // 4MB
    keepAliveInterval: 30000, // 30 seconds
    keepAliveTimeout: 5000, // 5 seconds
    enableKeepAlive: true,
  },
  debug: false,
};

/**
 * Merge user configuration with defaults
 */
export function createConfig(userConfig: ClientConfig): Required<ClientConfig> {
  return {
    ...DEFAULT_CONFIG,
    ...userConfig,
    retry: userConfig.retry ? { ...DEFAULT_CONFIG.retry, ...userConfig.retry } : DEFAULT_CONFIG.retry!,
    telemetry: userConfig.telemetry ? { ...DEFAULT_CONFIG.telemetry, ...userConfig.telemetry } : DEFAULT_CONFIG.telemetry!,
    grpc: userConfig.grpc ? { ...DEFAULT_CONFIG.grpc, ...userConfig.grpc } : DEFAULT_CONFIG.grpc!,
  } as Required<ClientConfig>;
}