package com.example.client.models;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.BeforeEach;

import static org.junit.jupiter.api.Assertions.*;

import com.fasterxml.jackson.databind.ObjectMapper;

/**
 * Unit tests for NewPet model
 * Generated by SDK Generator
 */
@DisplayName("NewPet Model Tests")
public class NewPetTest {
    
    private ObjectMapper objectMapper;
    private NewPet model;
    
    @BeforeEach
    void setUp() {
        objectMapper = new ObjectMapper();
        model = new NewPet();
    }
    
    @Test
    @DisplayName("Should set and get name")
    void testNameGetterSetter() {
        // Given
        String expectedValue = "test_value";
        
        // When
        model.setName(expectedValue);
        String actualValue = model.getName();
        
        // Then
        assertEquals(expectedValue, actualValue);
    }
    
    @Test
    @DisplayName("Should support fluent name setting")
    void testNameFluentSetter() {
        // Given
        String value = "test_value";
        
        // When
        NewPet result = model.withName(value);
        
        // Then
        assertSame(model, result);
        assertEquals(value, model.getName());
    }
    
    @Test
    @DisplayName("Should set and get tag")
    void testTagGetterSetter() {
        // Given
        String expectedValue = "test_value";
        
        // When
        model.setTag(expectedValue);
        String actualValue = model.getTag();
        
        // Then
        assertEquals(expectedValue, actualValue);
    }
    
    @Test
    @DisplayName("Should support fluent tag setting")
    void testTagFluentSetter() {
        // Given
        String value = "test_value";
        
        // When
        NewPet result = model.withTag(value);
        
        // Then
        assertSame(model, result);
        assertEquals(value, model.getTag());
    }
    
    @Test
    @DisplayName("Should set and get photoUrls")
    void testPhotoUrlsGetterSetter() {
        // Given
        List<String> expectedValue = /* TODO: generate test value */;
        
        // When
        model.setPhotoUrls(expectedValue);
        List<String> actualValue = model.getPhotoUrls();
        
        // Then
        assertEquals(expectedValue, actualValue);
    }
    
    @Test
    @DisplayName("Should support fluent photoUrls setting")
    void testPhotoUrlsFluentSetter() {
        // Given
        List<String> value = /* TODO: generate test value */;
        
        // When
        NewPet result = model.withPhotoUrls(value);
        
        // Then
        assertSame(model, result);
        assertEquals(value, model.getPhotoUrls());
    }
    
    @Test
    @DisplayName("Should serialize to JSON")
    void testSerialization() throws Exception {
        // Given
        NewPet model = new NewPet();
        // TODO: Set test data
        
        // When
        String json = objectMapper.writeValueAsString(model);
        
        // Then
        assertNotNull(json);
        assertFalse(json.isEmpty());
    }
    
    @Test
    @DisplayName("Should deserialize from JSON")
    void testDeserialization() throws Exception {
        // Given
        String json = "{}"; // TODO: Add valid JSON
        
        // When
        NewPet result = objectMapper.readValue(json, NewPet.class);
        
        // Then
        assertNotNull(result);
    }
    
    @Test
    @DisplayName("Should handle round-trip serialization")
    void testRoundTripSerialization() throws Exception {
        // Given
        NewPet original = new NewPet();
        // TODO: Set test data
        
        // When
        String json = objectMapper.writeValueAsString(original);
        NewPet deserialized = objectMapper.readValue(json, NewPet.class);
        
        // Then
        assertEquals(original, deserialized);
    }
    
    @Test
    @DisplayName("Should implement equals correctly")
    void testEquals() {
        // Given
        NewPet model1 = new NewPet();
        NewPet model2 = new NewPet();
        NewPet model3 = new NewPet();
        
        // TODO: Set same data for model1 and model2
        // TODO: Set different data for model3
        
        // When/Then
        assertEquals(model1, model2);
        assertNotEquals(model1, model3);
        assertEquals(model1, model1);
        assertNotEquals(model1, null);
        assertNotEquals(model1, "different type");
    }
    
    @Test
    @DisplayName("Should implement hashCode correctly")
    void testHashCode() {
        // Given
        NewPet model1 = new NewPet();
        NewPet model2 = new NewPet();
        
        // TODO: Set same data for both models
        
        // When/Then
        assertEquals(model1.hashCode(), model2.hashCode());
    }
    
    @Test
    @DisplayName("Should implement toString correctly")
    void testToString() {
        // Given
        NewPet model = new NewPet();
        
        // When
        String result = model.toString();
        
        // Then
        assertNotNull(result);
        assertTrue(result.contains("NewPet"));
    }
    
}
