"""
com.example.client Configuration
Generated by client-sdk-generator
"""

from dataclasses import dataclass
from typing import Optional, Dict, Any
import os


@dataclass
class ClientConfig:
    """Configuration for the com.example.client client."""

    base_url: str
    timeout: float = 30.0
    default_headers: Optional[Dict[str, str]] = None
    api_key: Optional[str] = None

    def __post_init__(self):
        """Initialize default values and environment variables."""
        if self.api_key is None:
            self.api_key = os.getenv("API_KEY")

        if self.default_headers is None:
            self.default_headers = {}

        if self.api_key:
            self.default_headers["Authorization"] = f"Bearer {self.api_key}"

    @classmethod
    def from_env(cls, base_url: Optional[str] = None) -> "ClientConfig":
        """Create configuration from environment variables."""
        return cls(
            base_url=base_url or os.getenv("API_BASE_URL", ""),
            timeout=float(os.getenv("API_TIMEOUT", "30.0")),
            api_key=os.getenv("API_KEY"),
        )
